### ISSUE TITLE
crash when pressing backspace on naming

### ISSUE THREAD

**Issue by jackytuutykcaj** [ArtixAllMighty/Telepads2016#10]
When placing down telepad and naming.
https://pastebin.com/2tmVbjsV

**Comment by AbsolemJackdaw** [comment]
thanks for the report. i'll look into fixin the 1.10.2 version when i'm done with 1.11.2 content addition !

**Comment by AbsolemJackdaw** [comment]
can't seem to reproduce the error. got a crash report ?

**Comment by AbsolemJackdaw** [comment]
closing this issue due to unresponsivity of interlocutor and inability on my end of reproducing the error
