### ISSUE TITLE
Crash using version 1.12

### ISSUE THREAD

**Issue by darrenhollick** [ArtixAllMighty/Telepads2016#13]
We created a fresh Forge 1.12 server and only installed your mod (and the mod dependency) and the crash report is attached.  

Only installed mods:
- sublib-1.11.2-1.1.4.1.jar
- telepads-1.11.2-1.0.2.0.jar

[crash-2017-06-27_17.48.32-server.txt](https://github.com/ArtixAllMighty/Telepads2016/files/1106915/crash-2017-06-27_17.48.32-server.txt)
I really hope you'll take the time to update the mod for version 1.12!

**Comment by AbsolemJackdaw** [comment]
i will update it. 
1.11 version doesn't work with 1.12
