### ISSUE TITLE
1.12 Server crashed when using Telepad in the End

### ISSUE THREAD

**Issue by sofifreak** [ArtixAllMighty/Telepads2016#16]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.0-beta1-1.12-anarchy.jar)
  BCModPlugin (backpacks 1.12 - 3.3.0.jar)
  HammerCoreCore (HammerCore-1.12-1.9.3.8.jar)
  LoadingPlugin ([1.12] VersionChecker-1.3.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.1.5.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  AppleCore (AppleCore-mc1.12-2.2.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.3.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 8/13/17 4:41 PM
Description: Ticking block entity

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at subaraki.telepads.tileentity.TileEntityTelepad.func_73660_a(TileEntityTelepad.java:147)
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at subaraki.telepads.tileentity.TileEntityTelepad.func_73660_a(TileEntityTelepad.java:147)

-- Block entity being ticked --
Details:
	Name: minecraft:tileentitytelepad // subaraki.telepads.tileentity.TileEntityTelepad
	Block type: ID #1786 (tile.telepads.telepad // subaraki.telepads.block.BlockTelepad)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (99,49,2), Chunk: (at 3,3,2 in 6,0; contains blocks 96,0,0 to 111,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #1786 (tile.telepads.telepad // subaraki.telepads.block.BlockTelepad)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Sofifreak'/263, l='world', x=99.52, y=49.25, z=2.70]]
	Chunk stats: ServerChunkCache: 423 Drop: 0
	Level seed: 1164529357510021144
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Linux (amd64) version 4.4.0-89-generic
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2439458248 bytes (2326 MB) / 3194093568 bytes (3046 MB) up to 3194093568 bytes (3046 MB)
	JVM Flags: 5 total; -Xms3096M -Xmx3096M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (server.jar) 
	UCHIJAAAA	forge{14.21.1.2443} [Minecraft Forge] (server.jar) 
	UCHIJAAAA	backpacks16840{3.3.0} [Backpacks!] (backpacks 1.12 - 3.3.0.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	versionchecker{1.3.0} [Version Checker] ([1.12] VersionChecker-1.3.0.jar) 
	UCHIJAAAA	antiqueatlas{4.4.4} [Antique Atlas] (antiqueatlas-1.12-4.4.4.jar) 
	UCHIJAAAA	applecore{2.2.2} [AppleCore] (AppleCore-mc1.12-2.2.2.jar) 
	UCHIJAAAA	baubles{1.5.1} [Baubles] (Baubles-1.12-1.5.1.jar) 
	UCHIJAAAA	bibliocraft{2.4.3} [BiblioCraft] (BiblioCraft[v2.4.3][MC1.12.0].jar) 
	UCHIJAAAA	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCHIJAAAA	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.12-1.5.1.jar) 
	UCHIJAAAA	cavern{1.10.0} [Cavern] (Cavern_1.12-v1.10.0.jar) 
	UCHIJAAAA	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCHIJAAAA	chisel{MC1.12-0.0.13.15} [Chisel] (Chisel-MC1.12-0.0.13.15.jar) 
	UCHIJAAAA	chiselsandbits{14.5} [Chisels & Bits] (chiselsandbits-14.5.jar) 
	UCHIJAAAA	shadowmc{3.8.0} [ShadowMC] (ShadowMC-1.12-3.8.0.jar) 
	UCHIJAAAA	clipboard{@VERSION@} [Clipboard] (Clipboard-1.12-1.3.0.jar) 
	UCHIJAAAA	codechickenlib{3.1.1.288} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.1.288-universal.jar) 
	UCHIJAAAA	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCHIJAAAA	cofhcore{4.3.3} [CoFH Core] (CoFHCore-1.12-4.3.3.11-universal.jar) 
	UCHIJAAAA	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.6-universal.jar) 
	UCHIJAAAA	discordchat{2.1.1} [Discord Chat] (DiscordChat-1.12-2.1.1.jar) 
	UCHIJAAAA	dldungeonsjdg{1.9.3} [Doomlike Dungeons] (DoomlikeDungeons-1.9.3-MC1.12.jar) 
	UCHIJAAAA	dsurround{3.4.6.3} [Dynamic Surroundings] (DynamicSurroundings-1.12-3.4.6.3.jar) 
	UCHIJAAAA	enderore{1.12-b1} [Ender Ore] (Ender Ore-1.12-b2.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.5.1.jar) 
	UCHIJAAAA	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCHIJAAAA	bigreactors{1.12-0.4.5.34} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.34.jar) 
	UCHIJAAAA	gottschcore{1.1.0} [GottschCore] (GottschCore-mc1.12-v1.1.0.jar) 
	UCHIJAAAA	fastladder{1.0.6} [FastLadder!] (FastLadder-mc1.12-v1.0.6.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.8.0-beta1-1.12-anarchy.jar) 
	UCHIJAAAA	ic2{2.8.14-ex112} [IndustrialCraft 2] (industrialcraft-2-2.8.14-ex112.jar) 
	UCHIJAAAA	jei{4.7.5.87} [Just Enough Items] (jei_1.12.1-4.7.5.87.jar) 
	UCHIJAAAA	forestry{5.5.0.154} [Forestry] (forestry_1.12-5.5.0.154.jar) 
	UCHIJAAAA	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UCHIJAAAA	gardenstuff{1.12-2.1.0} [Garden Stuff] (GardenStuff-1.12-2.1.0.jar) 
	UCHIJAAAA	goldcauldron{1.1} [Gold Cauldron] (goldcauldron-1.1.jar) 
	UCHIJAAAA	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCHIJAAAA	hammercore{1.9.3.8} [Hammer Core] (HammerCore-1.12-1.9.3.8.jar) 
	UCHIJAAAA	hopperducts{1.5} [Hopper Ducts] (hopperducts-mc1.12-1.5.jar) 
	UCHIJAAAA	waila{1.8.19} [Waila] (Hwyla-1.8.19-B33_1.12.jar) 
	UCHIJAAAA	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCHIJAAAA	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCHIJAAAA	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCHIJAAAA	jehc{1.3.0} [Just Enough HarvestCraft] (jehc-1.12-1.3.0.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	mantle{1.12-1.3.1.18} [Mantle] (Mantle-1.12-1.3.1.18.jar) 
	UCHIJAAAA	mcmultipart{2.2.2} [MCMultiPart] (MCMultiPart-2.2.2.jar) 
	UCHIJAAAA	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.9.jar) 
	UCHIJAAAA	refinedstorage{1.5.14} [Refined Storage] (refinedstorage-1.5.14.jar) 
	UCHIJAAAA	tconstruct{1.12-2.7.2.15} [Tinkers' Construct] (TConstruct-1.12-2.7.2.15.jar) 
	UCHIJAAAA	moartinkers{0.5.0} [Moar Tinkers] (moartinkers-0.5.0.jar) 
	UCHIJAAAA	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
	UCHIJAAAA	natura{1.12-4.3.0.10} [Natura] (Natura-1.12-4.3.0.10.jar) 
	UCHIJAAAA	nex{2.1.11.12} [NetherEx] (NetherEx-1.12-2.1.11.12.jar) 
	UCHIJAAAA	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.12-5.3.1.jar) 
	UCHIJAAAA	harvestcraft{1.12c} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12c.jar) 
	UCHIJAAAA	plants{1.2.0} [Plants] (Plants-1.12-1.2.0(1).jar) 
	UCHIJAAAA	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCHIJAAAA	refinedstorageaddons{0.1.1} [Refined Storage Addons] (refinedstorageaddons-0.1.1.jar) 
	UCHIJAAAA	rftools{6.12} [RFTools] (rftools-1.12-6.12.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8.jar) 
	UCHIJAAAA	rftoolsdim{5.04} [RFTools Dimensions] (rftoolsdim-1.12-5.04.jar) 
	UCHIJAAAA	ruins{16.7} [Ruins Mod] (Ruins-1.12.jar) 
	UCHIJAAAA	simplecorn{2.3.2} [Simple Corn] (SimpleCorn1.12-2.3.2(1).jar) 
	UCHIJAAAA	simplequarry{1.0.7} [Simple Quarry] (SimpleQuarry-1.12-1.0.7.jar) 
	UCHIJAAAA	simulatednights{1.12-2.1.0} [Simulated Nights] (simulatednights-1.12-2.1.0.jar) 
	UCHIJAAAA	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.1.0.jar) 
	UCHIJAAAA	subcommonlib{1.2.0.1} [Subaraki's Common Library] (subcommonlib-sublib-1.12-1.2.0.1.jar) 
	UCHIJAAAA	telepads{1.11.2-1.0.2.1} [Telepads] (telepads-1.12-1.0.2.1.jar) 
	UCHIJAAAA	thermalfoundation{2.3.3} [Thermal Foundation] (ThermalFoundation-1.12-2.3.3.10-universal.jar) 
	UCHIJAAAA	thermaldynamics{2.3.3} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.3.10-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.3.3} [Thermal Expansion] (ThermalExpansion-1.12-5.3.3.15-universal.jar) 
	UCHIJAAAA	waystones{4.0.12} [Waystones] (Waystones_1.12-4.0.12.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.5.1.jar)
  
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.0-beta1-1.12-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
BCModPlugin (backpacks 1.12 - 3.3.0.jar)
  brad16840.common.asm.ClassTransformer
HammerCoreCore (HammerCore-1.12-1.9.3.8.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
LoadingPlugin ([1.12] VersionChecker-1.3.0.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.1.5.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.12-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.3.jar)
  org.blockartistry.DynSurround.asm.Transformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 2; [EntityPlayerMP['Sofifreak'/263, l='world', x=99.52, y=49.25, z=2.70]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by AbsolemJackdaw** [comment]
Thanks for the report. the problem is being looked at and solved !
