### ISSUE TITLE
cant craft

### ISSUE THREAD

**Issue by gamergirl666** [ArtixAllMighty/Telepads2016#17]
im playing version 1.12 and i cant craft them is this an issue or can it not be done in this version?
![untitled](https://user-images.githubusercontent.com/31081095/29386428-aa383bf2-82d3-11e7-9cdd-456682e7af24.png)

**Comment by AbsolemJackdaw** [comment]
got a log ? maybe the recipe json is not being read?

**Comment by AbsolemJackdaw** [comment]
{
    "type": "minecraft:crafting_shaped",
    "group": "subaraki",
    "pattern": [
        "GGG",
        "EEE",
        "ICI"
    ],
    "key": {
        "G": { "item": "minecraft:glass" },
        "E": { "item": "minecraft:ender_pearl" },
        "I": { "item": "minecraft:iron_ingot" },
		"C": { "item": "minecraft:compass" }
    },
"result": {
        "item": "telepads:telepad"
	}
} 

the recipe states here that it is crafted with ingots.

**Comment by AbsolemJackdaw** [comment]
updated the wiki with a warning under the crafting recipe. 
you can alter the recipe json if you want to, opening the jar file with your favourite zip program
