### ISSUE TITLE
Adding an upgrade to a telepad doesn't consume the upgrade

### ISSUE THREAD

**Issue by CplPibald** [ArtixAllMighty/Telepads2016#19]
telepads-1.12-1.0.2.3

Place a telepad.  Then craft an upgrade (toggler or transmitter) and right-click.

**Expected**: upgrade stack is decremented (or deleted if there's only one item)
**Actual**: Upgrade is applied but stack is unchanged.

Breaking the telepad still returns the upgrade.  Repeatedly applying and breaking results in unlimited free upgrades.

**Comment by AbsolemJackdaw** [comment]
Thanks ! 
Testing and fixing this right now.
