### ISSUE TITLE
Clarification on the toggler

### ISSUE THREAD

**Issue by Winddbourne** [ArtixAllMighty/Telepads2016#20]
"Would you wish your friends, or other people, from not teleporting to a certain telepad, you can craft a Toggler Upgrade"

Reading this it is unclear what the toggler does . . . does this STOP your friends and other people from using your telepad or does it allow them to teleport to you?

Should it read:

"Would you wish to keep your friends, or other people, from teleporting to a certain pad"

or

"would you wish to allow your friends, or other people, to teleport to a certain pad"

I'm confused. lol

**Comment by AbsolemJackdaw** [comment]
applying a toggler to a telepad and powering said telepad will turn it off.

**Comment by AbsolemJackdaw** [comment]
adjusted wiki text, repalced "from not teleporting" with "to stop teleporting"
