### ISSUE TITLE
[Question] Way to teleport to a dimension without a telepad in it.

### ISSUE THREAD

**Issue by Boolyman** [ArtixAllMighty/Telepads2016#22]
Is there a way to set up a telepad to teleport you to a random or spawn location in a specified dimension that does not have a telepad already there?  Players in my modpack start in a special dimension, and I need a way to send them to the overworld after their tutorial.  I just want them to go to the overworld, I don't really care where, but there will not be a telepad in the overworld already.

**Comment by AbsolemJackdaw** [comment]
there is currently no such way.

**Comment by AbsolemJackdaw** [comment]
Looking to implement one

**Comment by AbsolemJackdaw** [comment]
I have this now completed and will upload a version of it to curseforge.

if you check this before the wiki, here's how the config file treats entries : 


teleport {
    # [x,y,z,dimension,locationName] locations can be defined exactly (100/64/100/0/Any Name really), with margin (-500#1000/64#128/0#500/-1#1,Some Location Name) or random (random/random/random/random/LocationNameHere). values can be mixed (-100#5000/random/100/0/yourLocationNameHere) is totally possible [default: ]
    S:"teleport locations" <
        100/70/100/0/100 TP
        -1000#5000/32#64/-1000#5000/-1/Nether Spawn
        random/64#128/random/0/random world location
     >
}

**Comment by Boolyman** [comment]
Great to see, thank you!
