### ISSUE TITLE
[mc1.12] [1.0.2.5] client crash when standing on telepad

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [ArtixAllMighty/Telepads2016#23]
client crash when standing on telepad
[crash-2017-10-09_10.29.04-server.txt](https://github.com/ArtixAllMighty/Telepads2016/files/1367911/crash-2017-10-09_10.29.04-server.txt)
latest forge for 1.12.0 used -> 14.21.1.2443

**Comment by AbsolemJackdaw** [comment]
did you or did you not add teleport locations into the config file, and if so, did you use the dev tool on said telepad that made the game crash ?

**Comment by 5t0rmr1d3r** [comment]
nope, we didnt changed the config file and we didnt use the dev tool.
we updatet our modpack to 1.12.2 and forge 14.23.0.2512.
the error still exists.

**Comment by AbsolemJackdaw** [comment]
have you tried deleting the old config so the game generates a new one ? 
something with the new feature is going wrong, and the crash is telling me the list is completely empty but exists.

try the config approach, and get back to em

**Comment by AbsolemJackdaw** [comment]
the lack of answer is regarded positively and this problem is being marked as solved.
