### ISSUE TITLE
Server chrashed wenn useing Telepad 1.12.2

### ISSUE THREAD

**Issue by sofifreak** [ArtixAllMighty/Telepads2016#24]
[crash-2017-10-10_22.48.45-server.txt](https://github.com/ArtixAllMighty/Telepads2016/files/1374789/crash-2017-10-10_22.48.45-server.txt)

**Comment by AbsolemJackdaw** [comment]
try deleting the old config and restart the game. if the error persists, please get back to me.

**Comment by AbsolemJackdaw** [comment]
in the absence of 'getting back to me', I will mark this problem as resolved
