### ISSUE TITLE
Possible make Telepad work for other people without Shift Right click ?

### ISSUE THREAD

**Issue by xfrankbx** [ArtixAllMighty/Telepads2016#25]
Hi, is it possible to make the telepads auto show up for multiple people without them needing to Shift and Right click ?
I was trying to use this as a multi-dimensional teleport system, but having to hand teleport people to each location just so they can Shift Right Click on the telepad is not going to work for me :-(

**Comment by 5t0rmr1d3r** [comment]
We also would like that to, something like a public / private function...

**Comment by AbsolemJackdaw** [comment]
You mean like a white list each player could make for themselfs ingame so when a pad is placed all of their 'friends' would have the location added automatically ? 

This might take a while, but i'll be looking into 'server pads'  : telepads that get registered to everyone joining a server.

**Comment by AbsolemJackdaw** [comment]
![](https://i.imgur.com/Ae79GIk.png)

![](https://i.imgur.com/eH5TKpY.png)

**Comment by AbsolemJackdaw** [comment]
Added a creative acces tool that allows operators to set telepads to public acces.
these will be synced to players when they step on a telepad.
 
This features stacks with dimensional and redstone upgrades

**Comment by AbsolemJackdaw** [comment]
added a whitelist. marking this topic as solved =)
