### ISSUE TITLE
Bug in 1.11.2 In Savana

### ISSUE THREAD

**Issue by Jymbo1984** [ArtixAllMighty/Telepads2016#26]
There is an error in version 1.11.2 When trying to put a name on a telepad in the Savannah plateau M biome the game crashe and suddenly closes but not in other biomes

**Comment by AbsolemJackdaw** [comment]
Sorry for the late reply, I would like to see a crash log for this to be able to help you. 

(im also currently updating and will be checking for this error myself)

**Comment by AbsolemJackdaw** [comment]
found the possible error. 
the textfield is made to only hold 16 characters, while Savannah Plateau M has 18.
Made a fix where any name exceeding 16 characters would return the 3 first letters of each word.

**Comment by Jymbo1984** [comment]
Unfortunately I lost the world and the reports in a format, but I would like to try it soon in a new world.
Thank you for your work
