### ISSUE TITLE
Telepads unable to be colored: latest 1.12.2

### ISSUE THREAD

**Issue by Akitori** [ArtixAllMighty/Telepads2016#27]
I mean this is probably a small bug, but trying to color the telepads appears to consume the dye and color it for a fraction of a second before losing the color. Except the dye isn't really consumed (pressing throw restores it) but the telepad still isn't colored. Also on that note.

Whenever a telepad is broken it has this long string of lore attached to it about colors and whatnot? Can that be fixed too?

**Comment by AbsolemJackdaw** [comment]
Found the lore issue, now tackling the coloring part

**Comment by AbsolemJackdaw** [comment]
I cannot find the coloring issue in the dev environment. will have to test later
