### ISSUE TITLE
Issue with Telepad upgrade

### ISSUE THREAD

**Issue by DatrixTHLK** [ArtixAllMighty/Telepads2016#3]
Hi Artix,

Not really sure if you noticed this already but the recipe for how to make the telepad upgrade within the game isn't showing.
Minecraft 1.10.2 
Forge 12.18.2.2022
JEI: 3.13.2.359
Sublib: 1.1.1.0
Telepad: 1.8.3

**Comment by AbsolemJackdaw** [comment]
which one ?

**Comment by DatrixTHLK** [comment]
Actually neither one. I figured out it was just user error because there is an item id listed telepad.upgrade.item and that is the toggler. I looked it up in FEI's subset menu list
