### ISSUE TITLE
BookShelf: Any

### ISSUE THREAD

**Issue by GettingYourGoat** [ArtixAllMighty/Telepads2016#31]
Whenever i attempt to play with this mod it gives me an error titled bookshelf: any

**Comment by AbsolemJackdaw** [comment]
I'd suggest you update the mod. Bookshelf was a requiered library for 1.7 ... 
The person I was working with retired from the team, and bookshelf got to many updates in a short span of time, so I saw fit removing it. 

try : 
"for people wondering about the 1.7.10 version, after much trial/crash/try again I seem to have got it working.

Using "Telepads-1.7.10 Bookshelf" together with Bookshelf version 1.1.0" 
([source](http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1292377-telepads-taking-teleports-to-a-whole-new-level?page=24#c478))

I no longer update or support 1.7. feel free to scoure the miencraft forum thread on telepads (its an official one, I just barely go to the site anymore) for people that found the solutions themself ! or for aid from anyone that might have encountered the same problems as you did
