### ISSUE TITLE
Update for 1.11.2

### ISSUE THREAD

**Issue by xfrankbx** [ArtixAllMighty/Telepads2016#32]
Can you release an update for 1.11.2 so the public functionality works with it ?  Thank you so much for this fix!

**Comment by AbsolemJackdaw** [comment]
nice title change x)

will try. will update my other mods first.
can't guarantee it'll work the same.

**Comment by xfrankbx** [comment]
LoL, yeah sorry on the title.  My Yubikey decided to submit that..
I am using JED (JustEnoughDimensions) right now with MC 1.11.2 but having to create "portals" using Command blocks to be able to teleport between dimensions.  I have had so many issues finding a teleportation system that works properly.  Yours worked great, until I logged in as another user and saw all the ones I setup were only for my other user LoL.  But when I saw you release the 1.12 update for public, I was hoping you could make it work on 1.11.2 as well since your portal system rocks!  :-)

**Comment by AbsolemJackdaw** [comment]
Dont know if i'll be able to update this to 1.11 due to time issues. 
Closing it for now. I hope the other mods will be able to upgrade to 1.12 !
