### ISSUE TITLE
Crashing through Telepads when attuning myself in Astral Sorcery

### ISSUE THREAD

**Issue by MiningPickaxe** [ArtixAllMighty/Telepads2016#33]
Hello,
when I attune myself in Astral Sorcery, my client crashes. Aparrently because of the telepad mod?! Not sure wich side causes this issue. Maybe you could take a look at it. https://pastebin.com/XJQsKMGW

**Comment by HellFirePvP** [comment]
you *could* just add as default a empty list here though like you did with that whitelist.
https://github.com/ArtixAllMighty/Telepads2016/blob/master/src/main/java/subaraki/telepads/capability/TelepadData.java#L22

**Comment by AbsolemJackdaw** [comment]
wonder why i never did ...

**Comment by MiningPickaxe** [comment]
I'm still crashing... even with the new version of the mod
https://pastebin.com/X6t7XS43
