### ISSUE TITLE
Crash with this mod

### ISSUE THREAD

**Issue by DatrixTHLK** [ArtixAllMighty/Telepads2016#34]
Minecraft 1.12.2
Forge: 14.23.3.2691
Sublib: 1.2.0.4
Telepads: 1.1.0.5

Hi Senpai,

I have a crash with this mod installed. This mod and [Vanilla Fix](https://minecraft.curseforge.com/projects/vanillafix) seem to be incompatible with one another or some other issue is involved as I tested this with the other 107 mods. I will make sure to tag @Runemoro about this as well in case it's on his side.
Crash Log: https://paste.dimdev.org/uduzojudaf.txt

**Comment by DatrixTHLK** [comment]
Issue on Vanilla Fix side, fixed by recent dev build.

**Comment by Runemoro** [comment]
By the way, the fact that this happened also means that there is also a bug in Telepads. VanillaFix adds a warning screen when a scheduled task throws an exception, but in this case the warning screen itself crashed, making a crash screen from VanillaFix.

The latest dev build will properly display the warning screen with the correct report for the issue.

**Comment by DatrixTHLK** [comment]
I will get the latest crash log to you Suberaki when the latest **dev build** of Vanilla Fix shows up on Curse Forge.

**Comment by DatrixTHLK** [comment]
I'm back! The latest crash log will be mentioned in my first post. And here also.

Crash Log: https://paste.dimdev.org/uduzojudaf.txt

**Comment by AbsolemJackdaw** [comment]
i traced the NPE and it doesnt look like the field receives a null value at any time. I've added a !null check and !isEmpty check on the list that throws the NPE. I hope it fixes stuff.

**Comment by DatrixTHLK** [comment]
Thanks, Senpai! I like this mod a lot
