### ISSUE TITLE
Changing GUI scale

### ISSUE THREAD

**Issue by PixelsGaming** [ArtixAllMighty/Telepads2016#35]
Whenever I use a TelePad, It changes my GUI scale, and I do not like that. Can anyone help me fix this?

VERSION: 1.7

**Comment by AbsolemJackdaw** [comment]
its a known issue in 1.7. you cannot change it. sorry
i've also dropped support for 1.7.
i hope you can update your MC soon , and that th other mods you use will be updated soon too !
