### ISSUE TITLE
Video Tutorial?

### ISSUE THREAD

**Issue by MrUnusual** [ArtixAllMighty/Telepads2016#36]
Good evening. I downloaded the TelePad mod for Minecraft, but I'm wanting to set certain TelePads to go to other certain TelePads automatically without giving me the list of TelePads to go to if that makes sense, I read the Admin/Server Dev Tools instructions, but did not really understand them, it pretty much shows that what I am wanting to do is possible, but the instructions on how to achieve this is hard to understand. 

An example of what I am wanting to do is create a TelePad that goes from the OverWorld to NetherRealm and vise versa and then another TelePad that goes from the OverWorld to EnderRealm and vise versa without having the option to travel from the EnderRealm to the NeatherRealm or from NeatherRealm to EnderRealm the using the same TelePad. I want certain TelePads to not show me the other TelePads in the list if that makes sense

**Comment by AbsolemJackdaw** [comment]
It makes total sense.

I suggets you try to reread this : 
https://github.com/ArtixAllMighty/Telepads2016/wiki/Server-Dev-Tools#itemtelepadstp_upgradename

it's from the wiki. this admin tool allows to turn a telepad into a One Way teleport. it won't show a gui, it won't show up in your personal, or anyone else's teleport list.
-you can then define a location to say, the nether, from the overworld. 
-to teleport back, you can put a telepad on the location you defined in the nether and make it a one way teleport to the overworld.

the only downside to this is that the locations have to be predefined in the config file. 

if you want everyone on a server to acces these telepads, you'll have to bring in another one and make it a public telepad, near the one way telepads. 

you cannot make a telepad both one way AND public. (well, not that i know of, you can always try)

public telepads will be listed to everyone on the server

if you have any more questions, please do ask !
