### ISSUE TITLE
[Small bug] Particle effect bug

### ISSUE THREAD

**Issue by SupremeMarshal** [ArtixAllMighty/Telepads2016#37]
This is just a small bug. When you step on an activated telepad, then deactivate it and step off from the telepad, the particle effect for when a player is stepping on stay there. Also, a deactivated telepad should have no particle effect as it is turned off. Beside from that, GREAT MOD! 👍

**Comment by AbsolemJackdaw** [comment]
Thanks for the observation, I'll make sure to tackle the issue !
