### ISSUE TITLE
Telepad + Void Dimension from Utility Worlds + Quartz Dimension from Dimensional Resources

### ISSUE THREAD

**Issue by DatrixTHLK** [ArtixAllMighty/Telepads2016#4]
Hi again, 

I put a telepad down on to a platform out of stone in the void dimension and I crashed to desktop because of it. I've crashed to desktop as well in the quartz dimension but booting the game back up works,

I don't really have a picture of the issue, but I did crash once I stepped on to the telepad.

Crash Log: https://gist.github.com/DatrixTHLK/b557b4368a25c1d4f18614928359df74
Minecraft: 1.10.2
Forge: 12.18.2.2151-3.2185
Sublib: 1.1.3.0
Telepads: 1.0.0.2
Utilitiy Worlds:  1.0.10
Dimensional Resources: 1.0.4

I'm going to send this over to Utility Worlds and Dimensional Resources. It could be on their end.

**Comment by AbsolemJackdaw** [comment]
might be their's indeed. how can the id 2 be out of range ? 
maybe it's on my end. very odd. i'll check on it.

**Comment by DatrixTHLK** [comment]
Thanks for the response. The quartz dimension only crashes me at random times and haven't experienced any crashes as of late. The crash happens when I'm in the gui for which telepad to teleport to which is very random and rare at least for the Quartz Dimension anyway. No other dimesions have this issue, at least not for Dimensional Resources.

**Comment by DatrixTHLK** [comment]
Still crashes with telepad being put into utility worlds void dimension. The crash renders the current save unplayable. Therefore I have to go back a save version in order to keep playing.

**EDIT:** And no I'm not trying to rush you just trying to update you on the current situation. I know you already know this, but someone else who is very sensitive will not and try to tell me off.

**Comment by AbsolemJackdaw** [comment]
currently looking into the bug, and updating to 1.11 at the same time. fix will be available for 1.11 if found

**Comment by ArtixAllMighty** [comment]
(also, got two similar issues, issue will be continued in other open issue)

**Comment by ArtixAllMighty** [comment]
any way of telling me where i can find those mods ?

**Comment by ArtixAllMighty** [comment]
the void dimension is for 1.7.10 ?

**Comment by AbsolemJackdaw** [comment]
Dimensional Resources only gives me 404's on curse. have contacted the utility worlds mod author.

**Comment by DatrixTHLK** [comment]
I'm unable to get into Dimensional Resources curse page also. It seems as though the mod was taken down for reasons unknown. Good thing I didn't delete it from my own mods folder in minecraft. I've taken a bit of a hiatus from minecraft. I'll be back soon though.

**Comment by DatrixTHLK** [comment]
Just curious as to if you found the issue with utility worlds dimension crash when putting the telepad into the void dimension?

**Comment by AbsolemJackdaw** [comment]
java.lang.IllegalArgumentException: Invalid dimension id 2

no, still not. havent been able to work on it though.

**Comment by DatrixTHLK** [comment]
Ok, thanks for letting me know. Hope all is well.

**Comment by AbsolemJackdaw** [comment]
i think i found a fix.... has it changed ? does it work now ?

**Comment by DatrixTHLK** [comment]
Oh! I'm sorry I took so long to get back to you. What version is it for 1.10? 1.11? 1.12?

**Comment by AbsolemJackdaw** [comment]
" ArtixAllMighty closed this in 58d5879 on 25 Apr"
probably 1.11 ?

**Comment by AbsolemJackdaw** [comment]
'telepads-1.11-1.0.1.1.jar' dates from 'Apr 25, 2017' , if you'd like to try that one, or a later release

https://minecraft.curseforge.com/projects/telepad/files/2411731

**Comment by DatrixTHLK** [comment]
I can try when I return home from work in a couple of hours. Sorry, again, for taking so long to get back to you.

**Comment by DatrixTHLK** [comment]
I tried it and have great news, it works! Thanks so much for fixing this issue for me. Again, I'm sorry for taking so long to get back to you.

**Comment by AbsolemJackdaw** [comment]
no problem ! i'm glad to know it works ! Have fun playing with a working mod :D

**Comment by DatrixTHLK** [comment]
You have my respect, Senpai. :D
