### ISSUE TITLE
[Issue] Destroyed telepad still mark the spot as a teleport location.

### ISSUE THREAD

**Issue by SupremeMarshal** [ArtixAllMighty/Telepads2016#41]
I destroyed a telepad in creative mode in my server and we could still teleport to the destroyed telepad location.

**Comment by AbsolemJackdaw** [comment]
Ill double check that.
Should not happen

**Comment by AbsolemJackdaw** [comment]
The teleport location stays around for those that have not destroyed the pad, and get the option to remove the entry too. This applies for public telepads. 
is your issue about private telepds ?

**Comment by AbsolemJackdaw** [comment]
Closing the issue due to lack of response. 
I'm assuming you found a solution due to this.
Feel free to re-open the issue if you haven't found a fix.
