### ISSUE TITLE
on the latest beta, it doesnt let me craft the transmitter upgrade or even place it

### ISSUE THREAD

**Issue by MichaelSFisher** [ArtixAllMighty/Telepads2016#42]

**Comment by AbsolemJackdaw** [comment]
Ill check it out.
Anything else ? Something that moght obstruct it ? Do you have a log ?

**Comment by AbsolemJackdaw** [comment]
I'm going to close this issue for now. the recipe .json files are available in the jar.
I'm going out on a limb here, theorising it's a conflict with another mod.
