### ISSUE TITLE
telepad block destroyed by the generation of a structure

### ISSUE THREAD

**Issue by Jojovador** [ArtixAllMighty/Telepads2016#45]
I put down a telepad, a structure has been generated on telepad. 
I have the place to tp, but i havent the telepad block. 
I want delete localisation but without telepad block i cant. 
so can I go into the files to delete it? 
if so, where is the document? 

thx, merci beaucoup 
Jojovador

**Comment by AbsolemJackdaw** [comment]
Normallement c przevu que tu peut enlever lentree du telepad dans l interface pour teleporter. Il ny a pas besoin du block.
Ceci dit, je parle pour la version courante de telepads, qui est le 1.12.2

**Comment by Jojovador** [comment]
Super, merci.
J'ai réussi à le supprimer.
Bien à vous
