### ISSUE TITLE
Wrong Transmitter Upgrade Texture

### ISSUE THREAD

**Issue by ChrisLTheNerd** [ArtixAllMighty/Telepads2016#48]
I placed the Transmitter on the telepad but the texture is not correct. I tried it with the latest forge and with and without optifine, I even tried re-downloading the mod but the problem is still there. 

![2020-05-27_14 49 36](https://user-images.githubusercontent.com/50182206/83060411-6b265900-a029-11ea-85d3-76476aeb12f8.png)

**Comment by AbsolemJackdaw** [comment]
odd. could you check the logs? if the regular texture isnt found, it should say so in the logs

**Comment by AbsolemJackdaw** [comment]
closing due to age and no response
