### ISSUE TITLE
Crafting in 1.14.4

### ISSUE THREAD

**Issue by Mxcrider** [ArtixAllMighty/Telepads2016#49]
There seems to be no way to craft a Teleplad in the 1.14.4 version. Checked with Jei and than manually tried to craft it but didnt work.

**Comment by AbsolemJackdaw** [comment]
the recipe may have been left out and it may already be fixed

**Comment by AbsolemJackdaw** [comment]
marking as fixed due to lack of response. 
this generally means stuff works now
