### ISSUE TITLE
Invalid Dimension ID crash

### ISSUE THREAD

**Issue by scottosx** [ArtixAllMighty/Telepads2016#5]
Crash for Dimension -2 which is a space station from Advanced Rocketry. Transmitter upgrade installed.
[crash-2016-12-28_17.33.36-client.txt](https://github.com/ArtixAllMighty/Telepads2016/files/676413/crash-2016-12-28_17.33.36-client.txt)

**Comment by AbsolemJackdaw** [comment]
-at subaraki.telepads.gui.client.GuiTeleport.func_73863_a(GuiTeleport.java:168)
    >String dimension_name = DimensionType.getById(dimension_ID).getName();

where dimension_ID = dimension_ID = player.world.provider.getDimension();

- provider code : 
 public int getDimension()
    {
        return this.dimensionId;
    }

what it means : standing on the telepad, opening the gui retrieves the dimension the player is in. it gets the idea of said dimension and uses that idea to look up it's name.

Now, either the dimension id's arent available client side, or minecraft itself is borked. 
looking into it now

**Comment by AbsolemJackdaw** [comment]
because 

DimensionType.getById(dimension_ID).getName(); isn't that complicated. 

the forge code itself : 

public static DimensionType getById(int id)
    {
        for (DimensionType dimensiontype : values())
        {
            if (dimensiontype.getId() == id)
            {
                return dimensiontype;
            }
        }

        throw new IllegalArgumentException("Invalid dimension id " + id);
    }

isn't that stupid. 

looking more into it
