### ISSUE TITLE
unable to add friend do to Character limitation [1.12.2]

### ISSUE THREAD

**Issue by Silencx** [ArtixAllMighty/Telepads2016#51]
I'm currently running the mod on a 1.12.2 server. I found out that there is a character limit for adding people. As most of the players on my server have a username exceeding this limit. They are unable to add others as friends.

**Comment by AbsolemJackdaw** [comment]
The character limit that i added has the same limit that minecraft playernames have

**Comment by AbsolemJackdaw** [comment]
https://minecraft.gamepedia.com/Player#:~:text=In%20Java%20Edition%2C%20usernames%20must,than%20once%20every%2030%20days.

https://github.com/ArtixAllMighty/Telepads2016/blob/master/src/main/java/subaraki/telepads/screen/WhiteListScreen.java#L128

**Comment by Silencx** [comment]
The problem is that when i put in there name without the /add infront of it wont allow me to add anyone. Just keeps giving me the message that the player doesnt exist. So when i use /add infront of the name the current limit is not long enough

**Comment by AbsolemJackdaw** [comment]
you dont need the /

https://github.com/ArtixAllMighty/Telepads2016/blob/8a1324694e1d8fc728797ed3acdaa8bcf4f29cb7/src/main/java/subaraki/telepads/capability/player/TelepadData.java#L212-L256

**Comment by AbsolemJackdaw** [comment]
The piece of code was to show that the add command is not counted into the playername length count. 
the field in which stuff can be typed also doesnt have a limit that restricts this. 

I'm going to close the issue due to the time that has passed, but feel free to open it again if you still haven't found an answer.

Question, you're both playing legitimate minecraft right ?

**Comment by Silencx** [comment]
Yes, we were all using a legitimate copy of minecraft. 

But I eventually decided to switch to the Waystones mod as it was better suited for the way that the group was playing on the server.

Its just weird that we got this bug as in your code it clear that technically it should work the way as intended.
