### ISSUE TITLE
Version problems

### ISSUE THREAD

**Issue by Electroblade** [ArtixAllMighty/Telepads2016#52]
Hi there,

I seem to have a problem with the latest update on Curseforge. When I run the beta version on Telepads, it works, but I can't craft the transmitter, this can be a conflict in recipes, I will check.

The main problem I have is when I run the latest release version it Minecraft crashes and states that Telepads is for version 1.14.4 and not 1.16.4.

**Comment by zISKo666** [comment]
Same 1.14.4 versioning problem here ...

**Comment by AbsolemJackdaw** [comment]
looks like the toml has reverted for some reason when i uploaded the file ... 
you can fix it by changing the range in the toml from 1.14.4 to 1.16.5
