### ISSUE TITLE
Unable to craft Ender Bead Necklace 

### ISSUE THREAD

**Issue by Irritated-Badger** [ArtixAllMighty/Telepads2016#53]
Minecraft Version: 1.16.5
Mod Version: 3.0.0.3
Forge Version: 36.2.0

Issue:
There is no crafting recipe for the Ender Bead Necklace, and the crafting recipe shown in the mod's description doesn't work.

**Comment by AbsolemJackdaw** [comment]
the necklace recipe is present in the 3.0.0.3 jar. 
quick fix would be to edit the recipe json for the necklace.
has your log any recipe loading errors in it ?

**Comment by AbsolemJackdaw** [comment]
the recipe has been fixed in 1.17. the ore tag has had a change and has been updated to reflect these changes.

fixed in 8b48f8f2299a4122a8c4d39fca820207bb3a6891 (near bottom)
