### ISSUE TITLE
[Crash 1.17.1] Multiple problems and crashes with Telepads

### ISSUE THREAD

**Issue by noncom** [ArtixAllMighty/Telepads2016#54]
Playing Limitless 4 modpack on the official server I put a Telepad on my base and the server immediately crashed: https://gist.github.com/Gbergz/3239c3d599e1ba03bc6f87493c342783.

Then it allowed me to log in and this was what I saw when I looked at the Telepad:
![image](https://user-images.githubusercontent.com/2920144/133938858-20019ba3-9d89-4a6c-bf0f-5501f8c66d9b.png)

I tried to break it but it crashed the server again. With the same problem. So removing the Telepad is not possible! 

Then I accidentally stood on the Telepad and the client started crashing. Each time I logged in I was immediately disconnected, while the server was showing this error (not crashing): https://gist.github.com/Gbergz/1eba9d6d523d196830ca471d212618eb.

And unfortunately, as you see, I placed it near the bed... so my mate, on respawning, was appearing right on top of it and crashing as well now. This kinda broke the game quite a bit.

We were able to fix it by admin-grade trickery (removing the telepad with a hack) but hey the mod definitely looks broken.

PS: The mod is reportedly working absolutely fine in singleplayer (but I didn't try). But judging by the exception it's rather some problem with the servers Java or something idk, since I've checked the class and it's definitely there in the jar. The server is on BisectHosting, just in case.

**Comment by AbsolemJackdaw** [comment]
Thats fucked up.
It couldn't find the TileEntity; more known as BlockEntity in later updates. 
which is a default minecraft thing.

I'll double check my code, and i'll try to update in dev to the latest forge to see if it has some important changes.
my first thought would be on a mod that messes with block placements somehow. 

the mod has been tested on servers, so it should be fine.
this may be a specific case of mod compat.
I'm on it

**Comment by AbsolemJackdaw** [comment]
Just updated forge in my dev environement and couldn't find any bugs or changes. 
I'm going to have to ask to try and find if any mod is throwing mod compat issues if you can.

**Comment by Gbergz** [comment]
Update: Server crash https://gist.github.com/Gbergz/0bb4b2a63a7a8fe273b579233a653ab4

**Comment by noncom** [comment]
I'll just add some info: this is a different issue about the servers JRE not having AWT libs.. recently these errors started happening for various mods and other causes, like loading images with `ImageIO` also causes this.. So the problem in general might be coming from some change in how BisectHosting sets up their JRE, like they don't have xwindows so why adding AWT to the installation... Well, wrong, they don't know Java, but apparently AWT is not an option for usage on servers for now...

**Comment by AbsolemJackdaw** [comment]
I use AWT java Colors to color the telepads. 
I dont know If i can change these out. I'll see what i can do.

**Comment by AbsolemJackdaw** [comment]
archiving the issue due to crash being server side lack of libraries. 
will try to find an alternative to awt if possible
