### ISSUE TITLE
damaged teleport

### ISSUE THREAD

**Issue by servicomcr** [ArtixAllMighty/Telepads2016#57]
Hello 

I have a user who damaged a teleport but the problem is that I cannot find the configuration file to be able to delete it and put the teleports back :( could you help me

**Comment by servicomcr** [comment]
1.16.5 forge

**Comment by AbsolemJackdaw** [comment]
what do you mean with damaged teleport ?

teleport locations are stored in the world by the way.
 there is no config to reset anything. 
a user can only remove teleport entries that are linked to his own name. if he wants to add a location back in, he's gotta right click the block again

**Comment by AbsolemJackdaw** [comment]
closing issue due to lack of detail.
feel free to reopen if more details can be given
