### ISSUE TITLE
Crash When Placing Telepad

### ISSUE THREAD

**Issue by timbrown81** [ArtixAllMighty/Telepads2016#6]
Just installed the mod today using latest version with Minecraft 1.11.2.  Crashed to desktop with the following error:

http://pastebin.com/R07HKrDw

**Comment by DingoX3** [comment]
Just received the same crash. I placed the telepad down, game immediately froze, then my screen turned light blue for a second, then crashed to desk-top.

full crash report here: http://pastebin.com/CHTKNwGB

Minecraft Version: 1.11.2
Forge Version: 13.20.02226
Telepads Version: 1.11-v1.0.1.0

**Comment by RedAlex** [comment]
Same for my server 
Anyone work on a fix?

http://pastebin.com/eZepVXnR

Minecraft : 1.11.2
1.11.2-forge1.11.2-13.20.0.2252
telepads-1.11-v1.0.1.0

**Comment by AbsolemJackdaw** [comment]
i'm on it.
*reads crash reports*

uuhm 
Caused by: java.io.FileNotFoundException: telepads:models/wardrobe.json

since when is there a wardrobe in telepads ? ._.
