### ISSUE TITLE
[1.12.2] Missing Texture for the Transmitter Model on a Telepad.

### ISSUE THREAD

**Issue by SonicX8000** [ArtixAllMighty/Telepads2016#61]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 3
jei_1.12.2-4.16.1.302
subcommonlib-sublib-1.12.2-1.2.0.4
telepads-1.12.2-1.1.0.7

Log:
[latest.log](https://github.com/ArtixAllMighty/Telepads2016/files/8151417/latest.log)

-----

![telepadtransmittermissingtexture](https://user-images.githubusercontent.com/36653806/155943489-4186c5dc-3d87-4f11-a868-54ba3a1e826a.png)

I dunno if you support 1.12 now-a-days, but apparently the Transmitter Texture is missing when placed on a Telepad. According to the log file, it says that it failed to load the texture.

*EDIT*
...might be nice for me to include a image, oops.

**Comment by AbsolemJackdaw** [comment]
There is indeed no more support for 1.12 when it comes to updates.
You read the log right. the game isn't finding the texture.
You could double check the jar file (you can open it with a zip program like 7zip or winrar)
check the path the game is looking for the texture, and see if the files contain any typos maybe. 
the images should be present. i'm suspecting there's a typo in the image name. 
if the files are absent, you could copy them out of a more recent version, and put them in the correct spot in your current jar file

**Comment by SonicX8000** [comment]
Reason why they don't load is because in the jar they are named incorrectly, the 'u' for 'upgrade' is uppercase. The log is looking for them being lowercase which is why they aren't found.

Inside the `jar\assets\telepads\textures\entity\tile\`...
![errorfound](https://user-images.githubusercontent.com/36653806/155966958-dc3fdcd2-173c-4aca-90b4-29392e8cafde.png)

Making the U lowercase aka "Upgrade" to "upgrade"...
![errorfixed](https://user-images.githubusercontent.com/36653806/155967422-5edfa994-7564-406a-aea6-030c727c0dce.png)

...and now the texture works correctly.
![telepadtransmitterfixedtexture](https://user-images.githubusercontent.com/36653806/155967765-0b9add22-486d-4836-80e6-4c6b94fdeff0.png)

```
telepad_dimensionupgrade.png
telepad_dimensionupgrade_2.png
telepad_dimensionupgrade_3.png
telepad_dimensionupgrade_4.png
```

Now... I dunno what the stance is with edited jars, even if it's just a bugfix.

**Comment by AbsolemJackdaw** [comment]
I'm glad you managed to solve the issue ! 
i may want to look into editing the current jar if its just a naming problem.
I'll try and see if i can do that if i get five minutes somewhere.

don't worry about edited jars. it is just the textures. you're not changing the mod fundamentally and there is no bad in changing the names for a fix.

**Comment by SonicX8000** [comment]
Alright then, and yea, it's just a rename of the names that I posted and the texture should load in correctly.

**Comment by SonicX8000** [comment]
Double Post, but... is this texture used anywhere? Reason I ask is due to an Uppercase D in the name.

```
telepad_frame_interDimension.png
```

The log file doesn't seem to show anything so unsure if it's used or not. The texture just shows as a white rectangle with two lines on the left & right sides.

**Comment by AbsolemJackdaw** [comment]
might be the one used when switched to public or general telepad. not 100% sure.
changing to a lower case can't hurt, as the game doesnt read upper case anymore . i believe its a change from 1.8 that i never managed to get around till after 1.12
