### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by that1polish** [ArtixAllMighty/Telepads2016#62]
what are the dependencies for this mod

**Comment by AbsolemJackdaw** [comment]
Depends on modloader and version 
Theyre specified on CF normally.
Forge has none, older versions have Sublib

Fabric has the fabric API and probably the cloth config. I cant remember on the top of my head

**Comment by that1polish** [comment]
Thanks

**Comment by that1polish** [comment]
> Depends on modloader and version Theyre specified on CF normally. Forge has none, older versions have Sublib
> 
> Fabric has the fabric API and probably the cloth config. I cant remember on the top of my head

quick suggestion add a item to go to a telepad anywhere on the server/world
