### ISSUE TITLE
Minecraft - Telepad mod crashing game.

### ISSUE THREAD

**Issue by suuripomo** [ArtixAllMighty/Telepads2016#65]
Using Telepad mod on  Minecraft version 1.18.1.  Able to craft Telepads but the game crashes when I place the telepad. When I restart the game the Telepad is present but doesn't work.

Crash error code: Error: java.lang.IncompatibleClassChangeError: Found interface net.minecraft.core.RegistryAccess, but class was expected
Exit Code: -

log as follows
[crash-2022-05-03_17.29.32-client.txt](https://github.com/ArtixAllMighty/Telepads2016/files/8663441/crash-2022-05-03_17.29.32-client.txt)
1

**Comment by AbsolemJackdaw** [comment]
it crashes because you are using the 1.18.2 telepads version in 1.18.1


Try the 1.18.1 version instead !
[https://www.curseforge.com/minecraft/mc-mods/telepad/files/3592671
](https://www.curseforge.com/minecraft/mc-mods/telepad/files/3592671
)

**Comment by AbsolemJackdaw** [comment]
on second look, it looks like you are using minecraft 1.18.2, and telepads 1.18.1
![image](https://user-images.githubusercontent.com/3628535/167705144-bc7a9c45-f6b5-4bed-8dd9-5a413ca86810.png)
please update to latest of telepads ! 
[https://www.curseforge.com/minecraft/mc-mods/telepad/files/3751523](https://www.curseforge.com/minecraft/mc-mods/telepad/files/3751523)

**Comment by suuripomo** [comment]
Thanks

**Comment by AbsolemJackdaw** [comment]
(transparency update : i removed all the personal info from your answer-by-mail. be careful answering by mail ! it includes all mail adresses, cc's and more info)

**Comment by suuripomo** [comment]
thanks again
