### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Psyffee** [ArtixAllMighty/Telepads2016#66]
Playing version 1.18, using Forge 1.18 and Telepads 1.18. I had Optifine 1.18 installed but deleted to see if it was the issue but my game continues to crash open opening the world 
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceKey.m_135782_()" because "this.dimension" is null
Exit Code: -1

**Comment by AbsolemJackdaw** [comment]
Did you start a new world or is this a version hop ?

**Comment by Psyffee** [comment]
Neither. I just added the mod to my world an hour or 2 ago.

**Comment by AbsolemJackdaw** [comment]
thanks for the report. people keep getting this crash but i have no clue where it comes from. 
everyone used to have optifine though.
I'm wondering if optifine messes with dimensional stuff to make variables nullable while they never should be. 
I also check for those either way ... 

got a log ?

**Comment by Psyffee** [comment]
Do you mean like a crash report?

**Comment by AbsolemJackdaw** [comment]
yes ! 
there's a log folder in your install directory. 
latest.log and crash log would be mighty helpful

**Comment by AbsolemJackdaw** [comment]
Ive just fired up forge 1.18.2 with the 1.18.2 mod (5.1.0.0) and wasn't able to recreate the crash :/

**Comment by AbsolemJackdaw** [comment]
closing stale issue.
no answer from original poster in three months. 

feel free to reopen if issue is persisting
