### ISSUE TITLE
mod failed to load correctly

### ISSUE THREAD

**Issue by CapitanDiabetes** [ArtixAllMighty/Telepads2016#67]
so, im trying to use the mod on 1.19 and im getting an error on launching minecraft, it says:
java.lang.reflect.InvocationTargetException: null

also, here is the crash report

[crash report.txt](https://github.com/ArtixAllMighty/Telepads2016/files/9089796/crash.report.txt)

**Comment by AbsolemJackdaw** [comment]
excuse me, but believe you send an empty file ?

**Comment by CapitanDiabetes** [comment]
I did, my bad, this is it
[crash report.txt](https://github.com/ArtixAllMighty/Telepads2016/files/9097972/crash.report.txt)

**Comment by AbsolemJackdaw** [comment]
do you happen to use any forge version over .94 ? 94 had braeking changes. if so, try 93 or lower
i'm looking into updating to a later version soon

**Comment by AbsolemJackdaw** [comment]
oh yeah i can see you're using 94
> [fmlcore-1.19-41.0.94

**Comment by raycoga** [comment]
Hi, i got the same error with the forge 1.19.2 - 43.1.3 and 1.19.2 - 43.1.1
[crash-2022-08-28_13.30.50-fml.txt](https://github.com/AbsolemJackdaw/Telepads2016/files/9440159/crash-2022-08-28_13.30.50-fml.txt)

**Comment by AbsolemJackdaw** [comment]
> Hi, i got the same error with the forge 1.19.2 - 43.1.3 and 1.19.2 - 43.1.1 [crash-2022-08-28_13.30.50-fml.txt](https://github.com/AbsolemJackdaw/Telepads2016/files/9440159/crash-2022-08-28_13.30.50-fml.txt)

telepads wasn't made for 1.19.2 yet, that update will be around soon
