### ISSUE TITLE
No name the telepad gui

### ISSUE THREAD

**Issue by GabrielAnase** [ArtixAllMighty/Telepads2016#68]
While placeing a telepad i dont have a gui to name it and its unusable

**Comment by AbsolemJackdaw** [comment]
mod version ? minecraft version ?

**Comment by GabrielAnase** [comment]
1.16.5/3.0.0.3

**Comment by GabrielAnase** [comment]
with a Stay True modpack

**Comment by AbsolemJackdaw** [comment]
i'm convicned the gui works in standalone. i'll be checking it later again though.
make sure to also contact the star true modpack makers to see if they disable something or have a compat issue with another mod that disables this one.

**Comment by AbsolemJackdaw** [comment]
if you still have this issue, please reopen the ticket. 
I cant recreate the bug and i'm also not finding an instance of your modpack anywhere to test with
