### ISSUE TITLE
[1.18.2] Preconfigured teleportation doesn't seem to work (creative rod)

### ISSUE THREAD

**Issue by MrNovado** [ArtixAllMighty/Telepads2016#72]
1. Set the TP points as such:

```
reflection_whitelisted_blocks = [
  "random/random/random/-1/RNether",
  "random/random/random/0/ROverworld",
  "random/random/random/1/REnd",
  "random/random/random/random/Unstable",
]
```

2. Place a telepad
3. Place a transmitter on top
4. Right click on with the creative rod
5. Get the message "Something-something... normalRnether" (don't remember the exact message, but there's no space b/w the message and the tpp-name)
6. See the particles appear
7. Stand on the pad
8. Nothing happens?

Am I doing something wrong here, or the feature no longer works? 🤔

**Comment by AbsolemJackdaw** [comment]
I'm going to need to double check on this. 

The feature should still work.
Even thought the places are correctly defined, a quick glance at the Wiki seems to reveal a discrepancy between formats ? 
The given teleport points are to be defined in the configuration file if I remember correctly, but i'll have to double check on that? 

i'll get back to you with some more info in a couple hours, when i'm off of work

**Comment by AbsolemJackdaw** [comment]
Computational issue... 
Turns out I accidentally flipped an 'is equal or smaller then' sign around... 
I'm checking if the length of the list is smaller then the cycle index, instead of checking if the cycle index is smaller then the list size. 

I'm going to fix this for 1.19 for sure, and i'll see what code for 1.18.2 i have lying around to apply the fix too as well !!

**Comment by AbsolemJackdaw** [comment]
There also seems to be an oversight of dimension ID changes. 
it's been a while that minecraft updated from integer dimension ID's to text ID's. 
so the ID's for the dimension are now 'overworld', 'the_nether' and 'the_end'. 

I'll update the config description as well as the wiki

**Comment by AbsolemJackdaw** [comment]
a fix has been made for 1.19.2 and been uploaded to curseforge (6.1.0.2)
a fix has been made for the latest 1.18 version, which is 1.18.2, the only one I still had a copy of, and has been uploaded to curseforge (5.1.0.1)

1.18.2 : https://www.curseforge.com/minecraft/mc-mods/telepad/files/4072766

**Comment by MrNovado** [comment]
>I'm going to fix this for 1.19 for sure, and i'll see what code for 1.18.2 i have lying around to apply the fix too as well !!

Thanks 😃  Patching 1.18.2 would be nice!

>so the ID's for the dimension are now 'overworld', 'the_nether' and 'the_end'

I assume teleporting to custom dimensions would still require numeric ID, right?

**Comment by AbsolemJackdaw** [comment]
patch for 1.18.2 was made

> I assume teleporting to custom dimensions would still require numeric ID, right?  

its all textual now. custom dimensions too. can be found ingame with autocomplete with commands, just like entity id names

**Comment by MrNovado** [comment]
Just tested it on 1.18.2, all works now (and with custom dimensions too) 😄 Thank you!
