### ISSUE TITLE
Can't take pad from crafting table

### ISSUE THREAD

**Issue by inkihh** [ArtixAllMighty/Telepads2016#8]
I can craft a telepad, but I can't take it off the crafting table - it would always jump back.

1.10.2 on Windows 7x64

**Comment by AbsolemJackdaw** [comment]
any other info to be added ? have you tried using only the telepads mod ? or was it on a server ? 

I cannot honestly not see how not being able to take a telepad out of a crafting table would correlate with anything I coded about the telepad. I'll check for it though.

**Comment by AbsolemJackdaw** [comment]
I'm going to write this of as unrelated to the Telepads mod.
